services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://application-project-team:postgres@db:5432/server-db
    ports:
      - 3000:3000
    networks:
      - app_network
  
  db:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: application-project-team
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server-db
    ports:
      - 5432:5432
    networks:
      - app_network

networks:
  app_network: