services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  
  db:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: application-project-team
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server-db
    ports:
      - 5432:5432
    networks:
      - app_network

networks:
  app_network: