name: Test

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        environment: test
        steps:
            - uses: actions/checkout@v4
            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Run tests
              env:
                NODE_ENV: test
                CLIENT_ID_GITHUB: ${{ env.CLIENT_ID_GITHUB }}
                CLIENT_SECRET_GITHUB: ${{ secrets.CLIENT_SECRET_GITHUB }}
                DATABASE_URL: ${{ env.DATABASE_URL }}
              run: bun test
